export const CHECK_LOGIN_STATE_REQUEST = 'app/CHECK_LOGIN_STATE_REQUEST';
export const CHECK_LOGIN_STATE_SUCCESS = 'app/CHECK_LOGIN_STATE_SUCCESS';
export const CHECK_LOGIN_STATE_FAIL = 'app/CHECK_LOGIN_STATE_FAIL';
